#ifndef __BASE_TYPE_H
#define __BASE_TYPE_H

/*********************
 *      INCLUDES
 *********************/
#include "project_config.h"
#include "stdint.h"
/*********************
 *      TPEDEFS
 *********************/
//电源类型
enum {
    POWER_TYPE_NONE = 0,
    POWER_TYPE_DC,
    POWER_TYPE_DC_WITH_BATT,
    POWER_TYPE_BATTERY, 
    POWER_TYPE_SUPPLY_BOX,   
};

//调光曲线
enum {
    CURVE_TYPE_LINEAR = 0,
    CURVE_TYPE_EXP,   
    CURVE_TYPE_LOG,
    CURVE_TYPE_S_SHAPE,    
    CURVE_TYPE_MAX,
};

//通讯类型
enum {
    COM_TYPE_WIFI = 0,
    COM_TYPE_BLE,
    COM_TYPE_NETWORK,    
    COM_TYPE_MAX,
};

//风扇模式
enum {
    FAN_MODE_SMART,
    FAN_MODE_HIGH,
    FAN_MODE_MEDIUM,
    FAN_MODE_SILENT,
    FAN_MODE_MAX,
};

//色纸品牌
enum {
    ROSCO = 0,
    LEE = 1,
    GEL_BRAND_MAX,
};

//LEE品牌系列
enum {
    LEE_COLOR_CORRECTION = 0,
    LEE_COLOR_FILTERS,
    LEE_COLOR_600S,
    LEE_COLOR_COS_FILTERS,
    LEE_COLOR_700S,
    LEE_COLOR_MAX,
};

//ROSCO品牌类型系列
enum {
    ROSCO_COLOR_CORRECTION = 0,
    ROSCO_COLOR_CALCOLOR,
    ROSCO_STORARO_SEL,
    ROSCO_CINELUX,
    ROSCO_COLOR_MAX,
};

enum {
    LEE_SUMS = LEE_COLOR_MAX,
    ROSCO_SUMS = ROSCO_COLOR_MAX,
};

//SOURCE类型
typedef enum{
	TUNGSTEN_BULB = 0,
	INCANDESCENT,
	HALOGEN,
	ANTIQUE_BULB,
	WARM_ANTIQUE_BULB,
	CHRISTMAS_LIGHTS,
	NIGHT_LIGHT,
	INFRARED_HEAT_LAMP,
	GROW_LIGHT,
	CFL_SOFT_WHITE,
	CFL_Bright_White,
	CFL_COOL_WhITE,
	CFL_DAYLIGHT,
	COOL_WHITE_1,
	COOL_WHITE_2,
	COOL_WHITE_3,
	WARM_WHITE,
	CFL_BLACKLIGHT,
	HMI,
	HIGH_PRESSURE_SODIUM,
	LOW_PRESSURE_SODIUM,
	MERCURY_VAPOR,
	METAL_HALIDE,
	CERAMIC,
	CARBON_ARC,
	XENON,
	CANDLE,
	GAS_FIRE,
	SUN_DIRECT,
	SUN_OVERCAST,
	SUN_BLUE_HOUR,
	MOBILE_PHONE,
	COMPUTER_MONITOR,
	ELECTROLUMONENCE,
	BLOW_TORCH,
	ROAD_FLARE,
	AMBER_CAUTION,
	GREEN_TRAFFIC_LIGHT,
	YELLOW_TRAFFIC_LIGHT,
	RED_TTRAFFIC_LIGHT,
	BLUE_GLOW_STICK,
	GREEN_GLOW_STICK,
	RED_GLOW_STICK,
	YELLOW_GLOW_STICK,
	PINK_GLOW_STICK,
	VIOLE_GLOW_STICK,
	SOURCE_MAX
}src_light_t;

enum {
    PARAM_SETTING_CCT = 0,
    PARAM_SETTING_HSI,
    PARAM_SETTING_GEL,
    PARAM_SETTING_SOURCE,
    PARAM_SETTING_RGB,
    PARAM_SETTING_XY,    
    PARAM_SETTING_MAX,
};
typedef uint8_t param_setting_type_t;

enum {
    TRIGGER_TYPE_LOOP = 1,
    TRIGGER_TYPE_PULSE = 2,
    TRIGGER_TYPE_BOTH = 3,
};
typedef uint8_t trigger_type_t;

enum {
    FREQUENCY_LEVEL_1 = 1,
    FREQUENCY_LEVEL_2 = 2,
    FREQUENCY_LEVEL_3 = 3,
    FREQUENCY_LEVEL_4 = 4,
    FREQUENCY_LEVEL_5 = 5,
    FREQUENCY_LEVEL_6 = 6,
    FREQUENCY_LEVEL_7 = 7,
    FREQUENCY_LEVEL_8 = 8,
    FREQUENCY_LEVEL_9 = 9,
    FREQUENCY_LEVEL_10 = 10,
    FREQUENCY_LEVEL_R = 11,
};
typedef uint8_t frequency_level_t;

enum {
    SPEED_LEVEL_1  = 1,
    SPEED_LEVEL_2  = 2,
    SPEED_LEVEL_3  = 3,
    SPEED_LEVEL_4  = 4,
    SPEED_LEVEL_5  = 5,
    SPEED_LEVEL_6  = 6,
    SPEED_LEVEL_7  = 7,
    SPEED_LEVEL_8  = 8,
    SPEED_LEVEL_9  = 9,
    SPEED_LEVEL_10 = 10,
    SPEED_LEVEL_R  = 11,
};
typedef uint8_t speed_level_t;

enum {
    DECAY_LEVEL_1  = 1,
    DECAY_LEVEL_2  = 2,
    DECAY_LEVEL_3  = 3,
    DECAY_LEVEL_4  = 4,
    DECAY_LEVEL_5  = 5,
    DECAY_LEVEL_6  = 6,
    DECAY_LEVEL_7  = 7,
    DECAY_LEVEL_8  = 8,
    DECAY_LEVEL_9  = 9,
    DECAY_LEVEL_10 = 10,
    DECAY_LEVEL_R  = 11,
};
typedef uint8_t decay_level_t;

enum {
    COLORS_TYPE_R = 0,
    COLORS_TYPE_B,
    COLORS_TYPE_R_B,
    COLORS_TYPE_B_W,
    COLORS_TYPE_R_B_W,
    COLORS_TYPE_MAX,
};
typedef uint8_t colors_type_t;

enum {
    COLORS_KIND_3 = 0,
    COLORS_KIND_6,
    COLORS_KIND_9,
    COLORS_KIND_12,
    COLORS_KIND_15,
    COLORS_KIND_18,
    COLORS_KIND_24,
    COLORS_KIND_36,
    COLORS_KIND_MAX,
};
typedef uint8_t colors_kind_t;

enum {
    CCT_RANGE_WARMER = 0,
    CCT_RANGE_NATURAL,
    CCT_RANGE_COOLER,
};
typedef uint8_t cct_range_t;

enum {
    COLOR_COMBINATION_CCT = 0,
    COLOR_COMBINATION_HUE,
    COLOR_COMBINATION_CCT_HUE,
};
typedef uint8_t color_combination_t;

enum {
    OUTPUT_MODE_CONST_OUTPUT = 0,
    OUTPUT_MODE_MAX_OUTPUT,
	OUTPUT_MODE_MAX_OUTPUT_SET,
    OUTPUT_MODE_TYPE_MAX,
};
typedef uint8_t output_mode_t;

//电动附件 electric accessories
enum electric_type
{
    ELECTRIC_ACCESSORY_NULL,
    ELECTRIC_FRESNEL = 1 << 0,  //电动菲涅尔
    ELECTRIC_YOKE = 1 << 1, //电动支架
};

enum {
    LANGU_EN = 0,
    LANGU_CHINESE = 1,
    LANGU_MAX
};
typedef uint8_t langu_t;

//DMX丢失行为
enum {
	
    DMX_LOSS_BEHAVIOR_HLS = 0,//  hold last setting
    DMX_LOSS_BEHAVIOR_BO  = 1, // black out
    DMX_LOSS_BEHAVIOR_FTB = 2,//fade to black
    DMX_LOSS_BEHAVIOR_HFO = 3,// hold 2min fade out
    DMX_LOSS_BEHAVIOR_MAX
};

//DMX配置扩展
enum {
    DMX_EXTENSION_ACC = 0,// 电动附件
    DMX_EXTENSION_FUNCTION  = 1, // 功能配置
};

//DMX顺滑模式
enum {
    DMX_FADE_CLOSE = 0,
    DMX_FADE_SMOOTH = 1,
    DMX_FADE_SUPER_SMOOTH = 2,
    DMX_FADE_SEL_MAX,
};

//屏幕保护设置
enum {
    SCREENSAVAR_SETTING_AFTER_30_MINS = 0,
    SCREENSAVAR_SETTING_AFTER_60_MINS,
    SCREENSAVAR_SETTING_AFTER_120_MINS,
    SCREENSAVAR_SETTING_NO,
    SCREENSAVAR_SETTING_MAX,
};

enum {
    DMX_PROFILE_NUMS = 22,
};

//定制光效类型
enum {
    CUSTOM_FX_TYPE_PIKER = 0,
    CUSTOM_FX_TYPE_MUSIC,
    CUSTOM_FX_TYPE_TOUCHBAR,
    CUSTOM_FX_TYPE_MAX,
};

//电动支架角度限制状态
enum {
    ELE_YOKE_ANGLE_LIMIT_OFF = 0,
    ELE_YOKE_ANGLE_LIMIT_ON = 1,
};

//终端电阻状态
enum {
    DMX_TEMINATION_OFF = 0,
    DMX_TEMINATION_ON = 1,
};

//演播厅模式
enum {
    STUDIO_MODE_OFF = 0,
    STUDIO_MODE_ON,
};

//工作模式
enum {
    WORK_MODE_SLAVE = 0,
    WORK_MODE_MASTER = 1,
};

//以太网工作状态
enum {
    ETH_STATIC_START = 0,
    ETH_DHCP_START,
	ETH_NUM_START,
};

//以太网universe状态
enum {
    ETH_UNIVERSE_AUTOMATIC = 0,
    ETH_UNIVERSE_ARTNET,
	ETH_UNIVERSE_SACN,
	ETH_UNIVERSE_OFF,
};

//定制光效子页面
enum {
    SUB_ID_CUSTOM_FX_LIST = 0,
    SUB_ID_CUSTOM_FX_CHOOSE,
    SUB_ID_CUSTOM_FX_LOADING,
    SUB_ID_FX_INTENSITY,
};

//定义电动附件子页面
enum
{
    SUB_ID_ACCESSORY_LIST = 0,
    SUB_ID_ELE_FRESNEL,
    SUB_ID_ELE_YOKE,
    SUB_ID_ELE_OPTICAL_ACCESS,
    SUB_ID_ELE_YOKE_BLOCK_CONFIRM,
    SUB_ID_ELE_YOKE_RESET_CONFIRM,
    SUB_ID_ELE_YOKE_ANGLE_LIMIT,
    SUN_ID_ELE_YOKE_LIMIT_CONFIRM,
    SUB_ID_ELE_NO_ACCESS_WRING,
    SUB_ID_ELE_NO_ACCESS_WRING1,
    SUB_ID_ELE_NO_YOKE_ANGLE_LIMIT,
    SUB_ID_ELE_NO_YOKE_ANGLE_LIMIT_ENTER,
    SUB_ID_ELE_NO_YOKE,
	SUB_ID_ELE_APTURE_NO_YOKE,
	SUB_ID_ELE_DEMO,
	SUB_ID_ELE_RESET,
	SUB_ID_ELE_RESET_STATE,
	SUB_ID_ACCESSORY_REGOGNITION,
};

//电动附件类型
enum
{
    ELE_NOT,
    ELE_FRESNEL,
    ELE_YOKE,
    ELE_20_Reflector,
    ELE_30_Reflector,
    ELE_50_Reflector,
    ELE_ACCESSORY_NUM,
};

//DMX模式子页面
enum {
    SUB_ID_DMX_ENTRY = 0,
	SUB_ID_DMX_STATUS,
    SUB_ID_DMX_ADDRESS,
    SUB_ID_DMX_SMOOTH,
    SUB_ID_DMX_LOSS_BEHAVIOR,
    SUB_ID_DMX_PROFILE,
	SUB_ID_DMX_EXTENSION,
    SUB_ID_DMX_TEMINATION,
};

//Update子页面
enum {
    SUB_ID_UPDATE_SETTING = 0,
    SUB_ID_UPDATE_CONFIRM,
    SUB_ID_FIRMWARE_VERSION,    
    SUB_ID_UPDATING,
    SUB_ID_UPDATE_OK,
    SUB_ID_UPDATE_FAILED,
    SUB_ID_NO_FIRMWARE,
    SUB_ID_NOT_FOUND_UPD_DEV,
    SUB_ID_U_DISK_FORMAT_ERR,
};

//产品信息子页面
enum {
    SUB_ID_PRODUCT_INFO = 0,
    SUB_ID_HARD_VERSION,
};

//屏保子页面
enum {
    SUB_ID_SCREENSAVER_LIST = 0,
    SUB_ID_SCREENSAVER_WARN,
};

//控制系统子页面
enum {
    SUB_ID_CTRL_SYS_LIST = 0,
    SUB_ID_BLE_SETTING, //BLE 设置 + 进度条 + 复位结果
    SUB_ID_LUMENRADIO_SETTING, //Lumenradio设置 + 配对        
    SUB_ID_ETHERNET_SETTING, //以太网 + 
    SUB_ID_BLE_RESET_CONFIRM,
    SUB_ID_BLE_RESETING,
    SUB_ID_BLE_RESET_FAILED,
    SUB_ID_BLE_RESET_OK,
    SUB_ID_LUMENRADIO_PAIRING,
    SUB_ID_LUMENRADIO_PAIR_SUCCEED,
    SUB_ID_LUMENRADIO_PAIR_FAILED,
    SUB_ID_LUMENRADIO_UNPAIR_CONFIRM,
	SUB_ID_LUMENRADIO_UNLINK_SUCCEED,
	SUB_ID_LUMENRADIO_LINK_SUCCEED,
	SUB_ID_LUMENRADIO_LINK_FAILED,
 	SUB_ID_LUMENRADIO_LINK_TICK,
    SUB_ID_ETHERNET_MANUAL_SET_IP,
	SUB_ID_ETHERNET_SATRT_SET_IP,
	SUB_ID_ETHERNET_UINVERSE_SET_IP,
	SUB_ID_ETHERNET_UINVERSE_STATE_SET,
	SUB_ID_ETHERNET_ARTNET_UINVERSE_SET,
	SUB_ID_ETHERNET_ARTNET_NET_SET,
	SUB_ID_ETHERNET_SACN_UINVERSE_SET,
};

//主从模式主界面
enum {
    SUB_ID_WORK_MODE_LIST = 0,
    SUB_ID_SYNC_CONFIRM,
	SUB_ID_SYNC_FOLLWO_MODE,
	SUB_ID_SYNC_UPDATA_SELECT,
	SUB_ID_SYNC_UPDATE_CONFIRM,
	SUB_ID_SYNC_UPDATAING,
	SUB_ID_SYNC_UPDATA_COMPLETE,
	SUB_ID_SYNC_UPDATE_FAILED,
    SUB_ID_SYNC_NO_FIRMWARE,
    SUB_ID_SYNC_NOT_FOUND_UPD_DEV,
    SUB_ID_SYNC_U_DISK_FORMAT_ERR,
};

//电池扩展功能选项的子页面
enum {
    SUB_ID_BATT_OPTION_LIST = 0,
    SUB_ID_ACTIVATE_BATT_CONFIRM = 1,
    SUB_ID_FULL_POWER_TIP,    
    SUB_ID_ACTIVATING,
    SUB_ID_ACTIVATE_SUCCESS,
    SUB_ID_ACTIVATE_FAILED,
    SUB_ID_FULL_POWER_CONFIRM,
    SUB_ID_BATTERY_NOT_SUPPORT,
};

//CRMX配对状态机
enum {
    LUMENRADIO_NO_PAIR = 0,
    LUMENRADIO_START_PAIR,
    LUMENRADIO_PAIRING,
    LUMENRADIO_PARIED_SUCCEED,
    LUMENRADIO_PARIED_FAILED,
};

//CRMX取消配对状态机
enum {
    LUMENRADIO_UNPAIR_IDLE = 0,
    LUMENRADIO_UNPAIR_START,
};

//固件升级状态机
enum {
    FIRMWARE_UPD_STATUS_IDLE,
    FIRMWARE_UPD_STATUS_START,
    FIRMWARE_UPD_STATUS_UPDING,
    FIRMWARE_UPD_STATUS_OK,
    FIRMWARE_UPD_STATUS_FAILED,
    FIRMWARE_UPD_STATUS_FAILED_NO_FW,    
    FIRMWARE_UPD_STATUS_FAILED_FORMAT_ERR,
};

//固件类型
enum {    
    FIRMWARE_TYPE_CTRL_BOX = 0,
    FIRMWARE_TYPE_LAMP,
	FIRMWARE_TYPE_BMP,
	FIRMWARE_TYPE_ELE_BRACKET,
    FIRMWARE_TYPE_ELE_FRNSEL,
#if USE_BOOT_UPDATING == 1
	FIRMWARE_TYPE_BOOT,
#endif
	FIRMWARE_TYPE_MAX,
//	FIRMWARE_TYPE_BOOT,
};

//电池状态
enum {
    BATT_STATE_IDLE,
    BATT_STATE_CHARGING,
    BATT_STATE_CHARGE_END, 
};

//电池方向
enum {
    BATT_LEFT,
    BATT_RIGHT,
};

//电池激活状态
enum {
    BATT_ACTIVATE_IDLE,
    BATT_ACTIVATE_START,
    BATT_ACTIVATE_ING,
    BATT_ACTIVATE_SUCCESS,
    BATT_ACTIVATE_FAILED,
};

//光效版本
enum {
    FX_VERSION_I = 0,
    FX_VERSION_II = 1,
};

enum {   
#if EFFECTS_USE_FIRE 
    ITEM_ID_FIRE = 0,
#endif
	
#if EFFECTS_USE_PAPARAZZI   
    ITEM_ID_PAPARAZZI,
#endif 
	
#if EFFECTS_USE_FAULT_BULB     
    ITEM_ID_FAULT_BULB, 
#endif 
	
#if EFFECTS_USE_TV 
    ITEM_ID_TV,
#endif  
	
#if EFFECTS_USE_PULSING 
    ITEM_ID_PULSING,
#endif
	
#if EFFECTS_USE_PARTY 
    ITEM_ID_PARTY,  
#endif  
	
#if EFFECTS_USE_CLUB_LIGHTS 
    ITEM_ID_CLUB_LIGHTS,   
#endif 

#if EFFECTS_USE_COLOR_CHASE 
    ITEM_ID_COLOR_CHASE,
#endif

#if EFFECTS_USE_CANDLE 
    ITEM_ID_CANDLE, 
#endif 

#if EFFECTS_USE_WELDING 
    ITEM_ID_WELDING, 
#endif  

#if EFFECTS_USE_COP_CAR 
    ITEM_ID_COP_CAR,
#endif

#if EFFECTS_USE_STROBE 
    ITEM_ID_STROBE,
#endif

#if EFFECTS_USE_LIGHTNING  
    ITEM_ID_LIGHTNING,
#endif  

#if EFFECTS_USE_FIREWORKS   
    ITEM_ID_FIREWORKS, 
#endif 

#if EFFECTS_USE_EXPLOSIONS    
    ITEM_ID_EXPLOSIONS , 
#endif
    ITEM_ID_MAX,
};


#endif // !__BASE_TYPE_H
